kind: Template
apiVersion: v1
metadata:
    name: echo-example
    annotations:
        description: 'An example ECHO (https://echo.labstack.com//) application written in Golang'
        tags: 'quickstart,golang'
        iconClass: icon-go-gopher
labels:
    template: echo-example
    app: echo-example
objects:
    - 
        kind: Service
        apiVersion: v1
        metadata:
            name: echo-example
            annotations:
                description: Exposes and load balances the application pods
        spec:
            ports:
                - 
                    name: web
                    port: 1323
                    targetPort: 1323
            selector:
                name: echo-example
    - 
        kind: Route
        apiVersion: v1
        metadata:
            name: echo-example
        spec:
            host: '${APPLICATION_DOMAIN}'
            to:
                kind: Service
                name: echo-example
    - 
        kind: ImageStream
        apiVersion: v1
        metadata:
            name: echo-example
            annotations:
                description: Keeps track of changes in the application image
    - 
        kind: BuildConfig
        apiVersion: v1
        metadata:
            name: echo-example
            annotations:
                description: Defines how to build the application
        spec:
            source:
                type: Git
                git:
                    uri: '${SOURCE_REPOSITORY_URL}'
                    ref: '${SOURCE_REPOSITORY_REF}'
                contextDir: '${CONTEXT_DIR}'
            strategy:
                type: Docker
            output:
                to:
                    kind: ImageStreamTag
                    name: 'echo-example:latest'
            triggers:
                - 
                    type: ConfigChange
                - 
                    type: GitHub
                    github:
                        secret: '${GITHUB_WEBHOOK_SECRET}'
    - 
        kind: DeploymentConfig
        apiVersion: v1
        metadata:
            name: echo-example
            annotations:
                description: Defines how to deploy the application server
        spec:
            strategy:
                type: Recreate
            triggers:
                - 
                    type: ImageChange
                    imageChangeParams:
                        automatic: true
                        containerNames:
                            - echo-example
                        from:
                            kind: ImageStreamTag
                            name: 'echo-example:latest'
                - 
                    type: ConfigChange
                    type: Github
                    github:
                        secret: "${GITHUB_WEBHOOK_SECRET}"
            replicas: 1
            selector:
                name: echo-example
            template:
                metadata:
                    name: echo-example
                    labels:
                        name: echo-example
                spec:
                    containers:
                        - 
                            name: echo-example
                            image: echo-example
                            ports:
                                - 
                                    containerPort: 8080
parameters:
    - 
        name: SOURCE_REPOSITORY_URL
        description: The URL of the repository with your application source code
        value: 'https://github.com/oviis/webserver-go-templates.git'
    - 
        name: SOURCE_REPOSITORY_REF
        description: 'Set this to a branch name, tag or other ref of your repository if you are not using the default branch'
    - 
        name: CONTEXT_DIR
        description: Set this to the relative path to your project if it is not in the root of your repository
    - 
        name: APPLICATION_DOMAIN
        description: The exposed hostname that will route to the Beego service
        value: echo-example.192.168.99.100.nip.io
    - 
        name: GITHUB_WEBHOOK_SECRET
        description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
        generate: expression
        from: '[a-zA-Z0-9]{40}'
